server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_po?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 7200
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

mybatis:
#  type-aliases-package: cn.mrcode.foodiedev.pojo    # 实体层
#  mapper-locations: classpath:mapper/*.xml          # mapper 层
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.guava: debug